"""initial migration

Revision ID: fa9e55e654fd
Revises: 
Create Date: 2024-04-14 10:50:00.727633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'fa9e55e654fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', mysql.LONGTEXT(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.Integer, nullable=True),
    sa.Column('product_id', sa.Integer, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_datas_id'), 'training_datas', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=190), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=190), nullable=True),
    sa.Column('password', sa.String(length=190), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('phone', sa.String(length=190), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('Models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=True),
    sa.Column('description', sa.String(length=190), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Models_id'), 'Models', ['id'], unique=False)
    op.create_table('model_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_path', sa.String(length=190), nullable=True),
    sa.Column('accuracy_result', sa.Float(), nullable=True),
    sa.Column('precision_result', sa.Float(), nullable=True),
    sa.Column('recall_result', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('mcc_result', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_product_id'), 'model_product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_product_id'), table_name='model_product')
    op.drop_table('model_product')
    op.drop_index(op.f('ix_Models_id'), table_name='Models')
    op.drop_table('Models')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_training_datas_id'), table_name='training_datas')
    op.drop_table('training_datas')
    # ### end Alembic commands ###
